= Android Bootcamp Training

17 February 2014

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/bootcamp-2014-02-17.git

or

   download a Zip archive by clicking the link at the top of the page or using the link:
  
	https://github.com/mailat/bootcamp-2014-02-17/zipball/master

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

== Homework Day 02

- prepare the wishes for the last day of course
- load the content of the loadForecastUrl in a String using HttpClient

......

city = "Novosibirsk"
city = city.replaceAll(" ", "%20");

//get the forecast of the next 5 days - http://api.openweathermap.org/data/2.5/forecast?q=Novosibirsk&ru&units=metric

loadForecastUrl = "http://api.openweathermap.org/data/2.5/forecast?q=" + city + "&ru&units=metric";

== Homework Day 03

- import in eclipse the Eclipse project 07_Sqlite and play with the example on emulator
- read on: http://developer.android.com/training/basics/data-storage/databases.html
